#!/bin/bash

export NAMESPACE=""
export PROJECT=""
export PROJECT_ROOT=`pwd`

export CONTEXT="handytool, firefox, javascript"

#export DB_CONNECTION=""
#export DB_SCHEMA=$NAMESPACE

export COMPOSE_FILE="docker-compose.yml"

export AMO_JWT_ISSUER=""
export AMO_JWT_SECRET=""
